### ISSUE TITLE
Linking errors when compiling driver.

### ISSUE THREAD

**Issue by fxrstor** [FilippTheBestDev/HideFiles#1]
I did everything as you mentioned but when compiling the drivers, there are 2 errors.
![image](https://github.com/FilippTheBestDev/HideFiles/assets/132809543/39346b46-f5fe-4b72-834c-e120935b73e1)
I fixed a few warnings and changed the assembly code to use `intrin.h` functions instead to change the CR0 register. (as mentioned by chatgpt). Other than that I didn't change anything. 
I can't find any information related to these errors nor I can find the library that exports these.
Any help?

**Comment by FilippTheBestDev** [comment]
Hello. That's an interesting question. Looking at the screenshot you've attached, most likely there is a problem with linking .obj files. Function `CompleteIrp` is implemented inside `processIoCtlCodes.cpp`. Is it possible that you've changed some includes (or maybe some source files aren't being compiled when you build project)?

**Comment by FilippTheBestDev** [comment]
I've looked more carefully at the code. It's strange that it complains about function `CompleteIrp` but not `ProcessIrp`. Maybe because `CompleteIrp` is defined as inline function? Hope you'll find out the reason ;)

**Comment by fxrstor** [comment]
Glad that you replied. I indeed modified some stuff only to fix the warnings and some errors. Additionally I can't use inline assembly in x64 so I either had to use intrinsic functions to modify the value of CR0 register or I had to create an external assembly file which contains the functions. I'll elaborate and show you what errors and warnings that I came across when I tried to compile the kernel. Also in steps to build you mentioned that we need to disable Treat warnings as errors, Spectre Mitigation, Why do we have to disable these, this seems risky to me. Is there any special reason to do them? I think you can think of adding a fix for the warnings.

**Comment by fxrstor** [comment]
Spectre Mitigations enabled, Treat errors as Warnings enabled.
Focus on the errors which are unreferenced formal parameters, type cast error and asm not supported on this architecture)
Ignore `UMApp` warnings, they're caused by user-mod app
![image](https://github.com/FilippTheBestDev/HideFiles/assets/132809543/c98d0bb0-6bfe-4323-9354-e1d7212c6ffe)
I fixed the unreferenced formal parameter error by adding `UNREFERENCED_PARAMETER(ParameterWhichIsCausingTheError);`
After adding the previous fix, the errors look much cleaner:
![image](https://github.com/FilippTheBestDev/HideFiles/assets/132809543/ec14df22-e5da-4e44-97eb-e71085ddf712)
I noticed the type cast both of the warnings point to the same code line which is 
`return (PULONG)InterlockedExchange(target, (LONG)hookaddr);`
where the `hookaddr` is `PUCHAR`. As for the inconsistent annotation, that doesn't seem to count in treat warnings as error.

These are problems which I am not quite sure of how to fix them. I asked ChatGPT about PUCHAR to LONG but it doesn't seem to get it right and about assembly code, I think you should add support for x64 bit as well.

_This is a newly created project, I've documented all the changes I've done in this one. Not related to previous project which is `DrvTest1`_

**Comment by FilippTheBestDev** [comment]
> Also in steps to build you mentioned that we need to disable Treat warnings as errors, Spectre Mitigation, Why do we have to disable these, this seems risky to me. Is there any special reason to do them?

I disabled "Treat warnings as errors" because of many type-cast and "unreferenced parameter" warnings, which i didn't want to fix. And "Spectre mitigation" was disabled because I didn't have Spectre libs, so it was a simple workaround. Also I haven't tried to compile this project for x64.

P.S.  Unfortunately, this project isn't being maintained anymore. It was never meant to work on x64 or newer Windows versions other than Windows 7. But if you're interested in this project, you can contribute to it, make pull requests, and I'll gladly accept the changes you've made.

**Comment by fxrstor** [comment]
Thanks for response. Closing this issue.
